# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LIFE-SHARE' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LIFE-SHARE
pod 'RxSwift', '~> 5'
pod 'RxCocoa', '~> 5'
pod 'RxAlamofire'
pod 'Toaster'
pod 'Kingfisher'

end
